version: '3.8'

services:

  bofa-nyc-pg:
    image: postgres:16
    ports:
      - "${BOFA_NYC_PG}:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_dumps/bofa_nyc:/docker-entrypoint-initdb.d

  moma-pg:
    image: postgres:16
    ports:
      - "${MOMA_PG}:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_dumps/moma:/docker-entrypoint-initdb.d

  socialite-media-pg:
    image: postgres:16
    ports:
      - "${SOCIALITE_MEDIA_PG}:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_dumps/socialite_media:/docker-entrypoint-initdb.d

  tech-forum-pg:
    image: postgres:16
    ports:
      - "${TECH_FORUM_PG}:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_dumps/tech_forum:/docker-entrypoint-initdb.d

  bofa-london-pg:
    image: postgres:16
    ports:
      - "${BOFA_LONDON_PG}:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - ./db_dumps/bofa_london:/docker-entrypoint-initdb.d